# Generated by Django 4.0.4 on 2022-05-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('as_a', models.CharField(max_length=50)),
                ('needs', models.CharField(max_length=255)),
                ('goals', models.CharField(max_length=255)),
            ],
        ),
    ]
